spring:
    profiles:
        active: dev

    datasource:
        driver-class-name: com.mysql.jdbc.Driver
        url: jdbc:mysql://127.0.0.1:3306/dbgirl?useUnicode=true&characterEncoding=UTF-8
        username: root
        password: 123456
    jpa:
        hibernate:
                ddl-auto: update
        show-sql: true

    #thymeleaf start
    thymeleaf:
        mode: HTML5
        encoding: UTF-8
        content-type: text/html
        #开发时关闭缓存,不然没法看到实时页面
        cache: false
        #thymeleaf end

    #uploadFileSize start
    #http:
    #    multipart:
    #        maxFileSize: 10Mb
    #        maxRequestSize: 100Mb
    #uploadFileSize end